### ISSUE TITLE
Does the script not work on Firefox?

### ISSUE THREAD

**Issue by BellSilver** [lolamtisch/KissAnimeList#43]
## Describe your issue:  

I tried adding it to firefox but there were errors on the script.

## Steps to reproduce:  

1.  
2.  

## Your settings:

**Browser**:  Firefox
**Userscript manager**:  greasemonkey
**Where did you encounter the issue:**  after "installing"

## Attachments:  

![image](https://user-images.githubusercontent.com/29493428/35820813-d3911b44-0a74-11e8-8cd1-f4dcbef2332f.png)

and lines 40-44 were all errors icon

**Comment by dinosw** [comment]
Greasemonkey is not officially supported (*the screenshot is from the [Greasyfork page](https://greasyfork.org/en/scripts/27564-kissanimelist)*).  
![From the Greasyfork page](https://i.imgur.com/iCYDUy9.png)  
You can also read about supported browsers and userscript-managers in the wiki-section "[Getting Started](https://github.com/lolamtisch/KissAnimeList/wiki/Getting-started)".

The problem is that Greasemonkey 4 is not backwards compatible with a lot of syntax used for scripts.  
You can read more about the Greasemonkey 4 update [here](https://www.greasespot.net/2017/09/greasemonkey-4-announcement.html).  

Please use a supported userscript-manager such as [Tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) or [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/).
___  
And the icons you mentioned, are btw. not error icons. Error icons are red with an x.  
You can read more about meta-keys [here](https://greasyfork.org/en/help/meta-keys) and [here](https://tampermonkey.net/documentation.php).  
Here is a screenshot showing the same lines in Tampermonkey:  
![](https://i.imgur.com/F45Um74.png)

**Comment by BellSilver** [comment]
So I can't use this script on firefox then?
Cause I did log in to MAL like normal but it's not showing up anything

**Comment by dinosw** [comment]
Sure you can, like I said, just use  [Tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) or [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/) instead of Greasemonkey.  
Many use this script in Firefox without any problems.
