### ISSUE TITLE
Is it not working anymore?

### ISSUE THREAD

**Issue by BellSilver** [lolamtisch/KissAnimeList#60]
## Describe your issue:  
I opened Firefox today and the script isn't working even though the script is running in the background when i click the tampermonkey icon. I also tried reinstalling the script as well. 

## Steps to reproduce:  

1.  
2.  

## Your settings:
Firefox 
**Browser**:  
**Userscript manager**:  tampermonkey
**Where did you encounter the issue:**  kissmanga and kissanime
http://kissanime.ru/Anime/Black-Clover-TV

## Attachments:  

![image](https://user-images.githubusercontent.com/29493428/39557215-ed73b120-4e53-11e8-97aa-16fe6e7ff07a.png)

![image](https://user-images.githubusercontent.com/29493428/39557255-2e6960ee-4e54-11e8-9e23-a56d8e45a5b4.png)

**Comment by lolamtisch** [comment]
I encountered a similar behavior in the past. Don't know why, but tampermonkey sometimes did not want to start the script. You can check if it really gets started with the key 'F12' and then in the console should be a line like 'KissAnimeList [0.92.3]'. if not, there is something wrong with tampermonkey. 

I could only fix it by removing the script completely and reinstalling it.
Because of that i switched to violentmonkey and hadn't a problem since.
https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/

Just try it with violentmonkey to be sure it is not a problem with the script

**Comment by BellSilver** [comment]
I have it installed but it's not working on violentmonkey.

**Comment by BellSilver** [comment]
It's working on kissanime but it's not showing on kissmanga now

**Comment by lolamtisch** [comment]
Could you enable the debugging on the settings page on miniMAL and then look if there is something in the console? (F12 and the console tab)
![image](https://user-images.githubusercontent.com/12599334/39633216-a73ea29a-4fb7-11e8-9f47-9f130158a163.png)

**Comment by BellSilver** [comment]
What am I looking for in the console? and I enabled the debugging and it still doesn't show on Kissmanga, but it does Kissanime

**Comment by lolamtisch** [comment]
I am sorry.
I totaly forgot about this Issue.
Does it work again?

If you want you can join my discord server ( live-chat ), as it is easier to communicate.
https://discordapp.com/invite/cTH4yaw
