### ISSUE TITLE
Support for anime planet

### ISSUE THREAD

**Issue by b1n4ryk1lla** [lolamtisch/KissAnimeList#68]
was wondering if it was possible to add anime planet https://www.anime-planet.com support for lists since MAL seems to not be coming back in the next decade lol i started moving all my lists there and would be awesome if KAL would auto update there as well

**Comment by lolamtisch** [comment]
I need a relation between MAL and anime-planet for this to work. Did not see any mapping between them, so this will probably never happen, because i wont build another database only for anime-planet. 

anilist for example has a mapping with the MAL id for every anime/manga. So it is very likely to get supported by KAL someday.

**Comment by dinosw** [comment]
Besides MAL, AniList and Kitsu are the ones which are most often used for syncing Anime/Manga watch/read statuses.
